"""Statistical tests for supervised model results saved as TSV files.

The module reads ``fold_results.tsv`` generated by
``train_emotiv_dl_metrics.py`` and writes statistical test summaries next to the
input file. It intentionally works from text logs, so test implementation can
be iterated without retraining neural networks.
"""

from __future__ import annotations

import argparse
import json
from itertools import combinations
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import friedmanchisquare, wilcoxon
from statsmodels.stats.contingency_tables import mcnemar

from src.paths import DEFAULT_OUT_DIR

DEFAULT_RESULTS_FILES = (
    DEFAULT_OUT_DIR / "logs" / "supervised" / "leave_one_series_out" / "fold_results.tsv",
    DEFAULT_OUT_DIR / "logs" / "supervised" / "mixed_stratified_fold" / "fold_results.tsv",
)

SUPPORTED_METRICS = ("accuracy", "balanced_accuracy", "mcc")
ALPHA = 0.05


def _parse_json_list(value: str) -> list[int]:
    parsed = json.loads(value)
    if not isinstance(parsed, list):
        raise ValueError(f"Expected JSON list, got: {value!r}")
    return [int(item) for item in parsed]


def load_fold_results(path: Path) -> pd.DataFrame:
    """Load a supervised fold-results TSV and parse prediction columns."""
    df = pd.read_csv(path, sep="\t")
    required = {
        "config",
        "fold_strategy",
        "fold",
        "fold_index",
        "model",
        "training_variant",
        "accuracy",
        "balanced_accuracy",
        "mcc",
        "y_true",
        "y_pred",
    }
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"{path} is missing required columns: {sorted(missing)}")

    df = df.copy()
    df["y_true"] = df["y_true"].map(_parse_json_list)
    df["y_pred"] = df["y_pred"].map(_parse_json_list)
    return df


def holm_adjust(p_values: list[float], alpha: float = ALPHA) -> tuple[list[float], list[bool]]:
    """Return Holm-adjusted p-values and reject decisions in original order."""
    if not p_values:
        return [], []

    indexed = sorted(enumerate(p_values), key=lambda item: item[1])
    adjusted_sorted = []
    running_max = 0.0
    m = len(indexed)

    for rank, (_original_idx, p_value) in enumerate(indexed, start=1):
        adjusted = min(1.0, (m - rank + 1) * p_value)
        running_max = max(running_max, adjusted)
        adjusted_sorted.append(running_max)

    adjusted_original = [0.0] * m
    reject_original = [False] * m
    for (original_idx, _p_value), adjusted in zip(indexed, adjusted_sorted):
        adjusted_original[original_idx] = adjusted
        reject_original[original_idx] = adjusted <= alpha

    return adjusted_original, reject_original


def _complete_metric_matrix(
    group: pd.DataFrame,
    metric: str,
) -> tuple[pd.DataFrame | None, str | None]:
    pivot = group.pivot_table(
        index="fold",
        columns="model",
        values=metric,
        aggfunc="first",
    ).dropna(axis=0, how="any")

    if pivot.shape[1] < 3:
        return None, "friedman_requires_at_least_3_models"
    if pivot.shape[0] < 2:
        return None, "friedman_requires_at_least_2_folds"
    return pivot, None


def run_friedman_and_wilcoxon(
    df: pd.DataFrame,
    metric: str,
    alpha: float = ALPHA,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Run Friedman and pairwise Wilcoxon+Holm tests per training variant."""
    if metric not in SUPPORTED_METRICS:
        raise ValueError(f"Unsupported metric {metric!r}. Use one of {SUPPORTED_METRICS}.")

    friedman_rows = []
    wilcoxon_rows = []
    group_cols = ["config", "fold_strategy", "training_variant"]

    for group_key, group in df.groupby(group_cols, sort=True):
        config, fold_strategy, training_variant = group_key
        pivot, skip_reason = _complete_metric_matrix(group, metric)
        if pivot is None:
            friedman_rows.append({
                "config": config,
                "fold_strategy": fold_strategy,
                "training_variant": training_variant,
                "metric": metric,
                "n_folds": 0,
                "n_models": 0,
                "statistic": np.nan,
                "p_value": np.nan,
                "skip_reason": skip_reason,
            })
            continue

        arrays = [pivot[column].to_numpy(dtype=float) for column in pivot.columns]
        statistic, p_value = friedmanchisquare(*arrays)
        friedman_rows.append({
            "config": config,
            "fold_strategy": fold_strategy,
            "training_variant": training_variant,
            "metric": metric,
            "n_folds": int(pivot.shape[0]),
            "n_models": int(pivot.shape[1]),
            "statistic": float(statistic),
            "p_value": float(p_value),
            "skip_reason": "",
        })

        pair_rows = []
        raw_p_values = []
        for model_a, model_b in combinations(pivot.columns, 2):
            values_a = pivot[model_a].to_numpy(dtype=float)
            values_b = pivot[model_b].to_numpy(dtype=float)
            try:
                test_result = wilcoxon(values_a, values_b, zero_method="wilcox")
                pair_stat = float(test_result.statistic)
                pair_p = float(test_result.pvalue)
                skip = ""
            except ValueError as exc:
                pair_stat = np.nan
                pair_p = 1.0
                skip = str(exc)

            pair_rows.append({
                "config": config,
                "fold_strategy": fold_strategy,
                "training_variant": training_variant,
                "metric": metric,
                "model_a": model_a,
                "model_b": model_b,
                "n_folds": int(pivot.shape[0]),
                "mean_a": float(np.mean(values_a)),
                "mean_b": float(np.mean(values_b)),
                "mean_diff_a_minus_b": float(np.mean(values_a - values_b)),
                "statistic": pair_stat,
                "p_value": pair_p,
                "skip_reason": skip,
            })
            raw_p_values.append(pair_p)

        adjusted, rejected = holm_adjust(raw_p_values, alpha=alpha)
        for row, p_adjusted, reject in zip(pair_rows, adjusted, rejected):
            row["p_holm"] = float(p_adjusted)
            row["reject_holm"] = bool(reject)
            wilcoxon_rows.append(row)

    return pd.DataFrame(friedman_rows), pd.DataFrame(wilcoxon_rows)


def _correctness(y_true: list[int], y_pred: list[int]) -> np.ndarray:
    if len(y_true) != len(y_pred):
        raise ValueError("y_true and y_pred lengths differ")
    return np.asarray(y_true, dtype=int) == np.asarray(y_pred, dtype=int)


def run_mcnemar_augmented_vs_not(df: pd.DataFrame, alpha: float = ALPHA) -> pd.DataFrame:
    """Compare augmented vs not_augmented for each model using McNemar's test."""
    rows = []
    group_cols = ["config", "fold_strategy", "model"]

    for group_key, group in df.groupby(group_cols, sort=True):
        config, fold_strategy, model = group_key
        augmented = group[group["training_variant"] == "augmented"].set_index("fold")
        plain = group[group["training_variant"] == "not_augmented"].set_index("fold")
        common_folds = sorted(set(augmented.index) & set(plain.index))

        if not common_folds:
            rows.append({
                "config": config,
                "fold_strategy": fold_strategy,
                "model": model,
                "n_folds": 0,
                "n_samples": 0,
                "both_correct": 0,
                "augmented_correct_not_augmented_wrong": 0,
                "augmented_wrong_not_augmented_correct": 0,
                "both_wrong": 0,
                "statistic": np.nan,
                "p_value": np.nan,
                "reject": False,
                "skip_reason": "missing_paired_augmented_not_augmented_folds",
            })
            continue

        both_correct = 0
        augmented_correct_plain_wrong = 0
        augmented_wrong_plain_correct = 0
        both_wrong = 0
        n_samples = 0
        skip_reason = ""

        for fold in common_folds:
            aug_row = augmented.loc[fold]
            plain_row = plain.loc[fold]
            if aug_row["y_true"] != plain_row["y_true"]:
                skip_reason = f"y_true_mismatch_in_fold_{fold}"
                break

            aug_correct = _correctness(aug_row["y_true"], aug_row["y_pred"])
            plain_correct = _correctness(plain_row["y_true"], plain_row["y_pred"])
            both_correct += int(np.sum(aug_correct & plain_correct))
            augmented_correct_plain_wrong += int(np.sum(aug_correct & ~plain_correct))
            augmented_wrong_plain_correct += int(np.sum(~aug_correct & plain_correct))
            both_wrong += int(np.sum(~aug_correct & ~plain_correct))
            n_samples += len(aug_correct)

        if skip_reason:
            rows.append({
                "config": config,
                "fold_strategy": fold_strategy,
                "model": model,
                "n_folds": len(common_folds),
                "n_samples": n_samples,
                "both_correct": both_correct,
                "augmented_correct_not_augmented_wrong": augmented_correct_plain_wrong,
                "augmented_wrong_not_augmented_correct": augmented_wrong_plain_correct,
                "both_wrong": both_wrong,
                "statistic": np.nan,
                "p_value": np.nan,
                "reject": False,
                "skip_reason": skip_reason,
            })
            continue

        table = [
            [both_correct, augmented_correct_plain_wrong],
            [augmented_wrong_plain_correct, both_wrong],
        ]
        if augmented_correct_plain_wrong + augmented_wrong_plain_correct == 0:
            statistic = 0.0
            p_value = 1.0
        else:
            result = mcnemar(table, exact=True)
            statistic = float(result.statistic)
            p_value = float(result.pvalue)

        rows.append({
            "config": config,
            "fold_strategy": fold_strategy,
            "model": model,
            "n_folds": len(common_folds),
            "n_samples": n_samples,
            "both_correct": both_correct,
            "augmented_correct_not_augmented_wrong": augmented_correct_plain_wrong,
            "augmented_wrong_not_augmented_correct": augmented_wrong_plain_correct,
            "both_wrong": both_wrong,
            "statistic": statistic,
            "p_value": p_value,
            "reject": bool(p_value <= alpha),
            "skip_reason": "",
        })

    return pd.DataFrame(rows)


def write_test_outputs(
    results_path: Path,
    metric: str,
    friedman_df: pd.DataFrame,
    wilcoxon_df: pd.DataFrame,
    mcnemar_df: pd.DataFrame,
) -> dict[str, Path]:
    output_dir = results_path.parent
    paths = {
        "friedman": output_dir / f"friedman_{metric}.tsv",
        "wilcoxon": output_dir / f"wilcoxon_holm_{metric}.tsv",
        "mcnemar": output_dir / "mcnemar_augmented_vs_not_augmented.tsv",
    }
    friedman_df.to_csv(paths["friedman"], sep="\t", index=False)
    wilcoxon_df.to_csv(paths["wilcoxon"], sep="\t", index=False)
    mcnemar_df.to_csv(paths["mcnemar"], sep="\t", index=False)
    return paths


def analyze_results_file(
    results_path: Path,
    metric: str,
    alpha: float = ALPHA,
) -> dict[str, Path]:
    df = load_fold_results(results_path)
    friedman_df, wilcoxon_df = run_friedman_and_wilcoxon(df, metric=metric, alpha=alpha)
    mcnemar_df = run_mcnemar_augmented_vs_not(df, alpha=alpha)
    return write_test_outputs(results_path, metric, friedman_df, wilcoxon_df, mcnemar_df)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Run Friedman, Wilcoxon-Holm, and McNemar tests from supervised fold_results.tsv files."
    )
    parser.add_argument(
        "--results-file",
        action="append",
        type=Path,
        help="Path to a fold_results.tsv file. Can be passed multiple times. Defaults to both supervised log locations.",
    )
    parser.add_argument(
        "--metric",
        choices=SUPPORTED_METRICS,
        default="balanced_accuracy",
        help="Fold-level metric for Friedman and Wilcoxon-Holm tests.",
    )
    parser.add_argument(
        "--alpha",
        type=float,
        default=ALPHA,
        help="Significance threshold.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    result_files = args.results_file or list(DEFAULT_RESULTS_FILES)

    for results_path in result_files:
        if not results_path.exists():
            print(f"Pomijam brakujący plik: {results_path}")
            continue

        print(f"\nAnaliza pliku: {results_path}")
        output_paths = analyze_results_file(results_path, metric=args.metric, alpha=args.alpha)
        for name, path in output_paths.items():
            print(f"  {name}: {path}")


def cli_entry_point():
    main()


if __name__ == "__main__":
    main()
